### ISSUE TITLE
Do changes as you want, make it more beautiful and interactive

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/PatilShreyas.github.io#7]
This issue is open for all Hactoberfest participants. Do changes as you wanted. Just remember don't make silly PRs. Try to make it more perfect, beautiful and interactive. Add more Design or fix existing things. See what happens next.

Regarding PR:
Open PR against branch `hack-experiment`.

**Comment by sapsa07** [comment]
I would like to work on this ...

**Comment by PatilShreyas** [comment]
You're welcome. Just state here what you want to implement, fork this repo,
do changes and open PR against `hack-experiment` branch.

**Comment by sapsa07** [comment]
Do You want some parallax and neon effects in your portfolio website.

**Comment by PatilShreyas** [comment]
Yeah. Anything will be accepted.

**Comment by alexandresc** [comment]
[PR](https://github.com/PatilShreyas/PatilShreyas.github.io/pull/20) for fixing a CSS bug
